## Question 1 :  Write a Python program to check whether a number is even or odd using conditional statements.

In [1]:
num = int(input("Enter a number: "))

if num % 2 == 0:
    print("Even")
else:
    print("Odd")

Enter a number:  12

Even

## Question 2 : Write a Python program to count how many times a number appears in a list.

Example List

[2,3,4,2,5,2]

In [3]:
numbers = [2, 3, 4, 2, 5, 2]

num = int(input("Enter the number to count: "))

count = numbers.count(num)

print("The number appears", count, "times")

Enter the number to count:  2

The number appears 3 times

In [6]:
import pandas as pd

df = pd.read_csv(r"C:\Users\Niharika\Downloads\retail_dataset  (1).csv")
df.head()

,Transaction ID,Customer ID,Product Category,Quantity,Price,Date,Region
0,T001,C015,Books,7.0,167.0,02-02-2023,North
1,T002,C004,Toys,4.0,374.0,17-02-2023,South
2,T003,C033,Furniture,8.0,1059.0,17-05-2024,South
3,T004,C047,Groceries,5.0,304.0,11-02-2024,South
4,T005,C022,Books,7.0,282.0,27-07-2024,West

## Question 3 :  Generate an array from 1 to 20 with step size 2.

In [7]:
import numpy as np

arr = np.arange(1, 21, 2)
print(arr)

[ 1  3  5  7  9 11 13 15 17 19]

## Question 4 : Create a new column called Revenue, where:

Revenue = Quantity × Price

Display the updated dataset with the new column.

In [8]:
df['Revenue'] = df['Quantity'] * df['Price']

df

,Transaction ID,Customer ID,Product Category,Quantity,Price,Date,Region,Revenue
0,T001,C015,Books,7.0,167.0,02-02-2023,North,1169.0
1,T002,C004,Toys,4.0,374.0,17-02-2023,South,1496.0
2,T003,C033,Furniture,8.0,1059.0,17-05-2024,South,8472.0
3,T004,C047,Groceries,5.0,304.0,11-02-2024,South,1520.0
4,T005,C022,Books,7.0,282.0,27-07-2024,West,1974.0
...,...,...,...,...,...,...,...,...
95,T096,C036,Furniture,10.0,2901.0,08-08-2023,North,29010.0
96,T097,C021,Clothing,9.0,1077.0,19-07-2024,North,9693.0
97,T098,C015,Clothing,7.0,643.0,13-08-2023,North,4501.0
98,T099,C005,Groceries,9.0,429.0,20-01-2024,South,3861.0
99,T100,C010,Furniture,8.0,1183.0,07-02-2024,North,9464.0

## Question 5 : Convert a 1D array into 2x3 matrix:

arr = np.array([1,2,3,4,5,6])

In [9]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

matrix = arr.reshape(2, 3)

print(matrix)

[[1 2 3]
 [4 5 6]]

## Question 6 : Slicing Data

Select first 10 rows

Select only "Product Category" and "Quantity" columns

In [10]:
# Select first 10 rows
df.head(10)

# Select only "Product Category" and "Quantity" columns
df[['Product Category', 'Quantity']]

   Product Category  Quantity
0             Books       7.0
1              Toys       4.0
2         Furniture       8.0
3         Groceries       5.0
4             Books       7.0
..              ...       ...
95        Furniture      10.0
96         Clothing       9.0
97         Clothing       7.0
98        Groceries       9.0
99        Furniture       8.0

[100 rows x 2 columns]

## Question 7 : Find all records where:

Region = "South" and Quantity > 2

In [11]:
df[(df['Region'] == 'South') & (df['Quantity'] > 2)]

,Transaction ID,Customer ID,Product Category,Quantity,Price,Date,Region,Revenue
1,T002,C004,Toys,4.0,374.0,17-02-2023,South,1496.0
2,T003,C033,Furniture,8.0,1059.0,17-05-2024,South,8472.0
3,T004,C047,Groceries,5.0,304.0,11-02-2024,South,1520.0
24,T025,C022,Electronics,9.0,751.0,29-08-2023,South,6759.0
32,T033,C022,Furniture,5.0,2707.0,24-06-2024,South,13535.0
39,T040,C004,Toys,4.0,778.0,31-07-2024,South,3112.0
40,T041,C041,Toys,9.0,NaN,12-11-2024,South,NaN
44,T045,C049,Clothing,10.0,934.0,28-01-2023,South,9340.0
55,T056,C010,Books,4.0,434.0,13-08-2023,South,1736.0
60,T061,C049,Sports,4.0,990.0,19-09-2024,South,3960.0
61,T062,C028,Clothing,6.0,1323.0,16-09-2023,South,7938.0
69,T070,C041,Electronics,9.0,711.0,13-08-2023,South,6399.0
70,T071,C020,Sports,8.0,408.0,22-08-2023,South,3264.0
76,T077,C025,Furniture,9.0,995.0,16-04-2024,South,8955.0
79,T080,C015,Toys,9.0,1061.0,23-04-2023,South,9549.0
90,T091,C011,Electronics,3.0,980.0,22-03-2023,South,2940.0
98,T099,C005,Groceries,9.0,429.0,20-01-2024,South,3861.0

## Question 8 : Display:

The first 10 rows of the dataset.

Rows 15 to 25.

In [12]:
# First 10 rows
df.head(10)

# Rows 15 to 25
df.iloc[15:26]

,Transaction ID,Customer ID,Product Category,Quantity,Price,Date,Region,Revenue
15,T016,C029,Clothing,5.0,639.0,17-05-2024,North,3195.0
16,T017,C004,Toys,2.0,423.0,02-02-2024,South,846.0
17,T018,C039,Toys,8.0,NaN,28-01-2024,NaN,NaN
18,T019,C022,Sports,6.0,1328.0,26-07-2023,East,7968.0
19,T020,C045,Toys,2.0,962.0,15-01-2023,South,1924.0
20,T021,C043,Books,NaN,516.0,07-07-2024,East,NaN
21,T022,C042,Electronics,1.0,1971.0,05-04-2024,East,1971.0
22,T023,C015,Beauty,10.0,174.0,21-11-2024,North,1740.0
23,T024,C012,Clothing,6.0,236.0,28-07-2024,West,1416.0
24,T025,C022,Electronics,9.0,751.0,29-08-2023,South,6759.0
25,T026,C023,Sports,1.0,902.0,17-07-2024,West,902.0

## Question 9 : Create a random array of 10 numbers and:

Find max and min

Sort the array

In [13]:
import numpy as np

arr = np.random.randint(1, 100, 10)

print("Array:", arr)
print("Maximum:", arr.max())
print("Minimum:", arr.min())
print("Sorted array:", np.sort(arr))

Array: [21 39 33  9 45 60 33 13 52 10]
Maximum: 60
Minimum: 9
Sorted array: [ 9 10 13 21 33 33 39 45 52 60]